package com.deloitte.test.guidedruleapp;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Client")
public class Client implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Age")
	private int age;
	@org.kie.api.definition.type.Label("Buy")
	private boolean buy;

	@org.kie.api.definition.type.Label("Policy List")
	private java.util.List<com.deloitte.test.guidedruleapp.Policy> policyList;

	@org.kie.api.definition.type.Label(value = "Message")
	private java.lang.String msg;

	public Client() {
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public boolean isBuy() {
		return this.buy;
	}

	public void setBuy(boolean buy) {
		this.buy = buy;
	}

	public java.util.List<com.deloitte.test.guidedruleapp.Policy> getPolicyList() {
		return this.policyList;
	}

	public void setPolicyList(
			java.util.List<com.deloitte.test.guidedruleapp.Policy> policyList) {
		this.policyList = policyList;
	}

	public java.lang.String getMsg() {
		return this.msg;
	}

	public void setMsg(java.lang.String msg) {
		this.msg = msg;
	}

	public Client(int age, boolean buy,
			java.util.List<com.deloitte.test.guidedruleapp.Policy> policyList,
			java.lang.String msg) {
		this.age = age;
		this.buy = buy;
		this.policyList = policyList;
		this.msg = msg;
	}

}